[telegram]
enabled = false
bot_token = ""
default_chat_id = ""

[whatsapp]
enabled = true
phone_country_code = "+39"
send_as_single_block = true

[discord]
enabled = false
webhook_url = ""
default_channel = ""
