"""
MODULO: Processore Logico - Zentra Core v2.5
DESCRIZIONE: Il 'motore di esecuzione'. Trasforma il pensiero dell'IA in azioni 
reali tramite plugin e filtra il testo per la sintesi vocale.
Supporta la nuova struttura a cartelle dei plugin (plugins/nome_modulo/main.py).
Brain unificato.
"""
import sys
import re
import os

import importlib.util
from core.llm import brain
from core.processing import filtri
from core.logging import logger
from core.i18n import translator

# Colori per i log a video
GIALLO = '\033[93m'
CIANO = '\033[96m'
ROSSO = '\033[91m'
RESET = '\033[0m'

# Variabile globale per mantenere i parametri hardware
config_attuale = {}

# Blacklist di tag da ignorare
BLACKLIST = ["titolo", "anima", "regole", "database", "status", "tag"]

# Mappatura per tag generici al modulo corretto
TAG_MAPPING = {
    "terminale": "system",
    "cmd": "system",
    "istruzione": "system",
    "apri": "system",
    "notepad": "system",
    "chrome": "system",
    "visual studio": "system",
    "sillytavern": "system",
    "desktop": "file_manager",
    "download": "file_manager",
    "documenti": "file_manager",
    "core": "file_manager",
    "plugins": "file_manager",
    "memory": "file_manager",
    "personality": "file_manager",
    "logs": "file_manager",
    "config": "file_manager",
    "main": "file_manager",
}

def configura(nuova_config):
    """Riceve la configurazione dal Main e la memorizza per le chiamate al cervello (Brain)."""
    global config_attuale
    config_attuale = nuova_config
    logger.info("[PROCESSOR] Hardware configuration synchronized.")

def _importa_plugin(modulo_nome):
    """
    Importa dinamicamente un plugin dalla nuova struttura a cartelle.
    Cerca in: plugins/nome_modulo/main.py
    """
    try:
        plugin_path = os.path.join("plugins", modulo_nome, "main.py")
        if not os.path.exists(plugin_path):
            logger.debug("PROCESSOR", f"Plugin {modulo_nome} not found in {plugin_path}")
            return None
        
        spec = importlib.util.spec_from_file_location(
            f"plugins.{modulo_nome}.main", 
            plugin_path
        )
        if spec is None:
            logger.debug("PROCESSOR", f"Unable to create spec for {modulo_nome}")
            return None
            
        plugin_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(plugin_module)
        logger.debug("PROCESSOR", f"Plugin {modulo_nome} imported successfully")
        return plugin_module
    except Exception as e:
        logger.errore(f"[PROCESSOR] Plugin import error for {modulo_nome}: {e}")
        logger.debug("PROCESSOR", f"Exception: {str(e)}")
        return None

def elabora_scambio(testo_utente, stato_voce):
    """Gestisce l'intera catena: IA -> Plugin -> Pulizia -> Risposta."""
    logger.info(f"[PROCESSOR] Input received: '{testo_utente}'. Calling brain...")
    logger.debug("PROCESSOR", f"Input received: '{testo_utente}' | Voice status: {stato_voce}")
    
    # 1. Genera risposta dall'IA
    logger.debug("PROCESSOR", "Calling brain.genera_risposta()")
    risposta_grezza = brain.genera_risposta(testo_utente, config_attuale)
    logger.debug("PROCESSOR", f"Raw response received: {len(risposta_grezza)} characters")
    logger.debug("PROCESSOR", f"Content: '{risposta_grezza[:200]}...'")
    
    logger.info("[PROCESSOR] Raw response generated by AI.")
    
    # 2. Analisi Tag Plugin - cerca TUTTI i tag [MODULO: comando] o [MODULO]
    logger.debug("PROCESSOR", "Searching for tags in response...")
    
    # Lista per memorizzare tutti i tag trovati
    tags_trovati = []
    
    # Cerca tag standard [MODULO: comando]
    matches_standard = re.findall(r'\[(\w+):(.*?)\]', risposta_grezza)
    for tag, azione in matches_standard:
        tags_trovati.append((tag.lower(), azione.strip(), "standard"))
        logger.debug("PROCESSOR", f"Standard tag found: {tag.upper()} -> '{azione}'")
    
    # Cerca tag semplici [MODULO] (senza i due punti)
    matches_semplici = re.findall(r'\[(\w+)\]', risposta_grezza)
    for tag in matches_semplici:
        # Evita duplicati se il tag è già stato trovato come standard
        if not any(t[0] == tag.lower() for t in tags_trovati):
            tags_trovati.append((tag.lower(), "", "semplice"))
            logger.debug("PROCESSOR", f"Simple tag found: {tag.upper()}")
    
    # Processa TUTTI i tag trovati
    for tag_originale, azione, tipo in tags_trovati:
        # Determina il modulo da chiamare (con mappatura)
        modulo_da_chiamare = tag_originale
        
        # Se il tag è "tag", cerca di capire il modulo dall'azione
        if tag_originale == "tag" and azione:
            # Prova a mappare l'azione a un modulo
            azione_pulita = azione.strip().lower()
            for keyword, modulo in TAG_MAPPING.items():
                if keyword in azione_pulita:
                    modulo_da_chiamare = modulo
                    logger.debug("PROCESSOR", f"Mapped 'tag' with action '{azione}' to module {modulo}")
                    break
            else:
                # Se non trova mappatura, ignora
                logger.debug("PROCESSOR", f"Tag 'tag' with action '{azione}' not mappable, ignored")
                continue
        
        if modulo_da_chiamare in BLACKLIST:
            logger.debug("PROCESSOR", f"Module {modulo_da_chiamare} blacklisted, ignored")
            continue
            
        logger.debug("PROCESSOR", f"Processing module {modulo_da_chiamare.upper()} (original tag: {tag_originale})")
        
        # Importa il plugin dalla nuova struttura a cartelle
        plugin_module = _importa_plugin(modulo_da_chiamare)
        
        if plugin_module and hasattr(plugin_module, "esegui"):
            logger.debug("PROCESSOR", f"Plugin {modulo_da_chiamare} has 'execute' function; calling with action: '{azione}'")
            print(f"{GIALLO}[SYSTEM] {translator.t('executing_module', module=modulo_da_chiamare.upper())}{RESET}")
            
            try:
                esito = plugin_module.esegui(azione)
                if esito:
                    logger.info(f"[PROCESSOR] Plugin {modulo_da_chiamare.upper()} output: {esito}")
                    logger.debug("PROCESSOR", f"Output: {esito}")
                    print(f"{CIANO}[OUTPUT {modulo_da_chiamare.upper()}]: {esito}{RESET}")
                else:
                    logger.debug("PROCESSOR", f"Plugin {modulo_da_chiamare} returned no output")
            except Exception as e:
                logger.errore(f"[PROCESSOR] Plugin execution error for {modulo_da_chiamare}: {e}")
                logger.debug("PROCESSOR", f"Execution exception: {str(e)}")
        else:
            logger.debug("PROCESSOR", f"Plugin {modulo_da_chiamare} not found or missing 'execute' function")
    
    if not tags_trovati:
        logger.debug("PROCESSOR", "No tags found in response")
    
        # 3. Pulizia per l'output video
    logger.debug("PROCESSOR", "Removing tags for video output")
    risposta_video = re.sub(r'\[.*?:.*?\]', '', risposta_grezza).strip()
    
    if not risposta_video:
        # Controlla se c'erano tag nella risposta originale
        if re.search(r'\[.*?\]', risposta_grezza):
            # C'erano tag, quindi probabilmente è stato eseguito un comando
            logger.debug("PROCESSOR", "Response contained only tags; command executed")
            risposta_video = translator.t('command_executed')
        else:
            # Nessun tag e nessuna risposta - problema col modello
            logger.warning("PROCESSOR", "Empty response received from model")
            risposta_video = translator.t('model_no_response_error')
    
    logger.debug("PROCESSOR", f"Final video response: {len(risposta_video)} characters")

    # 4. Preparazione Testo Vocale
    testo_pulito = ""
    if stato_voce:
        logger.debug("PROCESSOR", "Preparing text for speech synthesis")
        testo_pulito = filtri.pulisci_per_voce(risposta_video)
        logger.info("[PROCESSOR] Text filtered and prepared for speech synthesis.")
        logger.debug("PROCESSOR", f"Voice text: {len(testo_pulito)} characters")
        
    return risposta_video, testo_pulito