id: flusso_di_prova
name: Flusso di prova 🧪
description: Un flusso di prova con un allarme, l'ora attuale e una storia.
version: 1
enabled: true
trigger:
  type: manual
pipeline:
- id: delay_2_minutes
  action: LOGIC__delay
  params:
    seconds: 20
- id: play_alarm
  action: AUDIO__play_alarm
  params:
    sound: default
  depends_on:
  - delay_2_minutes
- id: get_current_time
  action: EXECUTOR__get_time
  output_as: current_time
  depends_on:
  - play_alarm
- id: delay_3_minutes
  action: LOGIC__delay
  params:
    seconds: 50
  depends_on:
  - get_current_time
- id: tell_story
  action: AUDIO__speak
  params:
    text: C'era una volta, in un regno lontano, un coraggioso cavaliere che partì
      per un'avventura epica. Dopo aver superato molte sfide, trovò un tesoro nascosto
      e tornò a casa come un eroe.
  depends_on:
  - delay_3_minutes
- id: final_message
  action: AUDIO__speak
  params:
    text: Questo è il tuo flusso di prova completato!
  depends_on:
  - tell_story
_meta:
  created_at: '2026-06-01T08:22:07.222835'
  updated_at: '2026-06-01T11:22:02.469114'
  last_run: '2026-06-01T11:22:02.368977'
