id: morning_routine_01
name: Morning routine 01
trigger:
  type: manual
pipeline:
- id: Notizie della giornata
  action: AI__prompt
  position:
    x: 216
    y: 386
  params:
    prompt: 'Cerca su internet, usando il modulo BROWSER le 3 notizie piu importanti
      della giornata, riassumile brevemente in tre righe. '
    save_to_chat: true
  output_as: notizie1
_meta:
  created_at: '2026-06-08T07:28:13.772859'
  updated_at: '2026-06-15T07:03:08.120928'
  last_run: '2026-06-15T06:31:20.202222'
areas: []
