id: new_flow_mpvejwlv
name: Procedura 1
trigger:
  type: manual
pipeline:
- id: audio__play_alarm_1
  action: AUDIO__play_alarm
  params:
    sound: mixkit-interface-hint-notification-911.wav
- id: audio__speak_1
  action: AUDIO__speak
  params:
    text: pronti a partire con il nuovo flusso
  depends_on:
  - audio__play_alarm_1
- id: system__chat_message_1
  action: SYSTEM__chat_message
  params:
    text: Operazione attivata. Allarme n.2
  depends_on:
  - audio__speak_1
- id: audio__play_alarm_3
  action: AUDIO__play_alarm
  params:
    sound: mixkit-high-tech-bleep-2521.wav
  depends_on:
  - audio__speak_3
- id: audio__play_alarm_2
  action: AUDIO__play_alarm
  params:
    sound: universfield-simple-notification-152054.mp3
  depends_on:
  - system__chat_message_1
- id: audio__speak_3
  action: AUDIO__speak
  params:
    text: Controllo cartelle sul desktop, apro command. Fine del flusso
  depends_on:
  - ai__prompt_1
- id: audio__speak_2
  action: AUDIO__speak
  params:
    text: Ora controllo il meteo
  depends_on:
  - audio__play_alarm_2
- id: ai__prompt_1
  action: AI__prompt
  params:
    prompt: Controlla il meteo, e dimmi quale è il tempo per domani. poi apri la console
      command e dimmi quante cartelle ci sono sul desktop.
    save_to_chat: true
  depends_on:
  - audio__speak_2
_meta:
  created_at: '2026-06-01T18:14:45.016789'
  updated_at: '2026-06-01T18:14:45.016789'
