id: new_flow_mpv78mhf
name: zobbia 1
trigger:
  type: manual
pipeline:
- id: audio__speak_1
  action: AUDIO__speak
  params:
    text: ciao, sono hecos!! Partenza con il flusso di prova!
  depends_on:
  - ai__prompt_2
- id: system__chat_message_1
  action: SYSTEM__chat_message
  params:
    text: ciao, sono hecos da chat!
  depends_on:
  - audio__speak_1
- id: ai__prompt_2
  action: AI__prompt
  params:
    prompt: devi dire che adesso si parte con un'altra boiata nello stile di admin
    save_to_chat: <bool>
- id: ai__prompt_1
  action: AI__prompt
  params:
    prompt: 'fai una ricerca su google: donne con il seno enorme. Poi fammi vedere
      i risultati.'
    save_to_chat: true
  depends_on:
  - system__chat_message_1
- id: system__chat_message_2
  action: SYSTEM__chat_message
  params:
    text: tutto fatto, padrone.
  depends_on:
  - ai__prompt_1
_meta:
  created_at: '2026-06-01T14:43:35.730003'
  updated_at: '2026-06-01T17:51:00.895962'
  last_run: '2026-06-01T17:51:00.809658'
enabled: true
