id: onboarding
name: 🚀 Onboarding
description: Invia un promemoria ai nuovi utenti per completare il loro profilo con
  dati essenziali come email e città di residenza.
version: 1
enabled: true
trigger:
  type: manual
pipeline:
- id: executor__execute_background_command_1
  action: EXECUTOR__execute_background_command
  position:
    x: 413
    y: -86
_meta:
  created_at: '2026-06-08T15:35:01.279057'
  updated_at: '2026-06-10T17:20:01.720507'
  last_run: '2026-06-08T15:40:03.552828'
areas: []
